services:
  app:
    build: .
    container_name: gestion-app
    depends_on:
      - db
    volumes:
      - ./.env:/var/www/.env
    networks:
      - gestion_net
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: gestion-nginx
    depends_on:
      - app
    ports:
      - "8000:8000"
    networks:
      - gestion_net
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: gestion-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_segura
      MYSQL_DATABASE: gestion
      MYSQL_USER: gestion_user
      MYSQL_PASSWORD: gestion_pass
    volumes:
      - gestion_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - gestion_net

volumes:
  gestion_db:

networks:
  gestion_net:
    driver: bridge